Repository wecode-bootcamp-korea/17-2nd-CLASS404-frontend, pull requests merged in 2021-03, with the labels that each got.

#7 [17기 이사랑] Navigation 레이아웃 완료
  package-lock.json
  package.json
  public/images/logo.svg
  public/images/profile.png
  public/index.html
  src/Components/Navigation/Navigation.js
  src/Components/User/User.js
  src/Pages/Main/Main.js
  src/Routes.js
  src/styles/GlobalStyles.js
Labels: Status: 리뷰 요청

#6 [17기 박정현] Refactoring: 리뷰 내용 반영완료 / Conflict 해결 완료
  public/index.html
  src/Pages/Login/Login.js
  src/Pages/Signup/Signup.js
  src/config.js
  src/signInData.js
  src/signUpData.js
  src/styles/GlobalStyles.js
Labels: Status: 리뷰 요청

#10 [17기 이사랑] Main 페이지 레이아웃 및 통신 완료 - 머지 요청
  public/data/categoryData.json
  public/data/productListData.json
  public/data/sortingData.json
  public/favicon.png
  public/index.html
  src/Components/CategoryModal/Button/Button.js
  src/Components/CategoryModal/CategoryModal.js
  src/Components/Checkbox/Checkbox.js
  src/Components/Filter/Filter.js
  src/Components/Navigation/Navigation.js
  src/Components/Product/Product.js
  src/Components/ProductList/ProductList.js
  src/Components/RadioBtn/RadioBtn.js
  src/Components/SortingModal/SortingModal.js
  src/Components/Tag/Tag.js
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#12 [17기 박정현] Add: 리뷰 업로드 페이지 레이아웃 완료 & 컨플릭트 해결완료
  package-lock.json
  package.json
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ReveiwUpload/ReviewUpload.js
  src/Routes.js
  src/config.js
  src/index.js
Labels: Status: Accepted

#8 [17기 박정현](제품 상세 페이지) Refactoring: 리뷰 내용 반영 완료
  public/data/ProductMockData.json
  src/Pages/ProductDetail/MenuAside.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ReviewSection.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#14 [17기 이사랑] 마이페이지 레이아웃 및 통신 완료
  public/data/mypageData.json
  src/Components/CategoryModal/CategoryModal.js
  src/Components/Checkbox/Checkbox.js
  src/Components/Navigation/Navigation.js
  src/Components/Product/Product.js
  src/Components/RadioBtn/RadioBtn.js
  src/Components/User/User.js
  src/Pages/Main/Main.js
  src/Pages/MyPage/Components/Aside/Aside.js
  src/Pages/MyPage/Components/Blank/Blank.js
  src/Pages/MyPage/Components/MenuLink/MenuLink.js
  src/Pages/MyPage/Components/MenuTitle/MenuTitle.js
  src/Pages/MyPage/Components/MyPageBuy/MyPageBuy.js
  src/Pages/MyPage/Components/MyPageCreate/MyPageCreate.js
  src/Pages/MyPage/Components/MyPageLike/MyPageLike.js
  src/Pages/MyPage/Components/MyPageList/MyPageList.js
  src/Pages/MyPage/Components/MyPageMain/MyPageMain.js
  src/Pages/MyPage/Components/Title/Title.js
  src/Pages/MyPage/Components/UserInfo/UserInfo.js
  src/Pages/MyPage/MyPage.js
  src/Pages/MyPage/Pages/MyPageBuy/MyPageBuy.js
  src/Pages/MyPage/Pages/MyPageCreate/MyPageCreate.js
  src/Pages/MyPage/Pages/MyPageLike/MyPageLike.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Routes.js
  src/config.js
  src/styles/GlobalStyles.js
Labels: Status: 수정 요청, Status: 컨플릭트 해결 요청

#11 [17기 이지은] Footer 머지요청
  .env
  package-lock.json
  src/Components/Navigation/Navigation.js
  src/Pages/Components/Footer/Footer.js
  src/Pages/Components/Footer/Footer.scss
  src/Pages/Main/Main.js
  src/styles/GlobalStyles.js
Labels: Status: 리뷰 요청

#9 [17기 이지은] 크리에이터 어플라이 머지 요청
  .env
  package-lock.json
  package.json
  public/images/productCreateLogo.png
  src/Components/.env
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Pages/CreatorApply/CreatorApply.js
  src/Pages/CreatorApply/CreatorApply.scss
  src/Routes.js
  src/config.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: Accepted
